name = "therawvibes"
main = "src/index.ts"
compatibility_date = "2024-10-01"

routes = [
  { pattern = "therawvibes.com/*", zone_name = "therawvibes.com" }
]

[env.staging]
name = "therawvibes-staging"